package DoAn;

import static DoAn.FrmConnect.Address;
import static DoAn.FrmConnect.Host;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author NHATNGUYEN
 */
public class FrmMa extends javax.swing.JFrame {

    /**
     * Creates new form FrmMa
     */
    public FrmMa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        btnKetNoiMa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Mã Phòng :");

        btnKetNoiMa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnKetNoiMa.setText("Kết Nối");
        btnKetNoiMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKetNoiMaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnKetNoiMa, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKetNoiMa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKetNoiMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKetNoiMaActionPerformed

        if (txtMa.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Không được để trống mã","Inane warning", JOptionPane.WARNING_MESSAGE);
        }  else {
            String MaPhong = txtMa.getText().trim();
            try {
                DatagramSocket sk = new DatagramSocket();
                InetAddress server = InetAddress.getByName(Address);
                String KT="KTMA";
                byte[] data0 = KT.getBytes();
                DatagramPacket KeyMP = new DatagramPacket(data0, data0.length, server, Host);
                byte[] data = MaPhong.getBytes();
                DatagramPacket mp = new DatagramPacket(data, data.length, server, Host);
                sk.send(KeyMP);
                sk.send(mp);
                byte[] buffer = new byte[5000];
                DatagramPacket dataRecieve = new DatagramPacket(buffer, buffer.length);
                sk.receive(dataRecieve);
                String ketQua = new String(dataRecieve.getData(), 0, dataRecieve.getLength());
                if (ketQua.equals("MAOKE")) {
                    JOptionPane.showMessageDialog(this, "Kết nối thành công vào nhóm chat !");
                    this.setVisible(false);
                    FrmChat fmChat = new FrmChat();
                    fmChat.setVisible(true);

                }
                else{
                     JOptionPane.showMessageDialog(this, "Mã phòng không chính xác vui lòng nhập lại!","Inane warning", JOptionPane.WARNING_MESSAGE);
                     txtMa.setText("");
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Kết nối thất bại vui lòng kiểm tra lại địa chỉ và port !","Inane warning", JOptionPane.WARNING_MESSAGE);

            }
        }
    }//GEN-LAST:event_btnKetNoiMaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKetNoiMa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtMa;
    // End of variables declaration//GEN-END:variables
}
